class AppError(Exception):
    def __init__(self, code, message, *, expose=False, cause=None, status=None):
        super().__init__(message)
        self.code = code
        self.expose = expose
        self.cause = cause
        self.status = status


class ErrorCodes:
    DISCORD_CONNECTION = "DISCORD_CONNECTION"
    CONFIG = "CONFIG"
    PINECONE_AUTH = "PINECONE_AUTH"
    PINECONE_UNAVAILABLE = "PINECONE_UNAVAILABLE"
    NAMESPACE_NOT_CONFIGURED = "NAMESPACE_NOT_CONFIGURED"
    EMBEDDING_FAILED = "EMBEDDING_FAILED"
    GENERATION_FAILED = "GENERATION_FAILED"
    EMPTY_RESULTS = "EMPTY_RESULTS"
    MISSING_CHUNK_TEXT = "MISSING_CHUNK_TEXT"
    DISCORD_REPLY = "DISCORD_REPLY"
    MESSAGE_TOO_LONG = "MESSAGE_TOO_LONG"
    DB_UNAVAILABLE = "DB_UNAVAILABLE"
    DB_AUTH = "DB_AUTH"
    EMPLOYEE_NOT_FOUND = "EMPLOYEE_NOT_FOUND"
    EMPLOYEE_INACTIVE = "EMPLOYEE_INACTIVE"
    EMPLOYEE_DUPLICATE = "EMPLOYEE_DUPLICATE"
    LEAVE_TYPE_INVALID = "LEAVE_TYPE_INVALID"
    LEAVE_BALANCE_MISSING = "LEAVE_BALANCE_MISSING"
    INSUFFICIENT_LEAVE = "INSUFFICIENT_LEAVE"
    LEAVE_REQUEST_MISSING = "LEAVE_REQUEST_MISSING"
    LEAVE_REQUEST_PROCESSED = "LEAVE_REQUEST_PROCESSED"
    LEAVE_REQUEST_OPEN = "LEAVE_REQUEST_OPEN"
    LEAVE_REQUEST_WITHDRAWN = "LEAVE_REQUEST_WITHDRAWN"
    LEAVE_DATES_APPROVED = "LEAVE_DATES_APPROVED"
    HR_PERMISSION = "HR_PERMISSION"
    INVALID_DATES = "INVALID_DATES"
    LEAVE_NO_WORKING_DAYS = "LEAVE_NO_WORKING_DAYS"
    LEAVE_NOT_AVAILABLE = "LEAVE_NOT_AVAILABLE"
